import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Headers';
import Main from '../components/Main';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Decentralized Lottery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Main />
    </div>
  )
}
