import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Headers'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Decentralized Lottery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      hello 
      <Header />
    </div>
  )
}
